[project]
name = "vobiz_system_call"
version = "0.0.1"
description = "Browser softphone extension for Vobiz Click To Call"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [
    { name = "SRIAAS", email = "webdevelopersriaas@gmail.com" }
]
dependencies = []

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["vobiz_system_call*", "frappe_crm*"]
namespaces = false

[tool.bench.frappe-dependencies]
frappe = ">=15.0.0,<16.0.0"
vobiz_click_to_call = ">=0.0.1"

[tool.ruff]
line-length = 110
target-version = "py310"
